######################## common config : ########################
#服务器配置
server:
  #获取异常信息
  error:
    include-exception: true
  port: 8080

#spring配置
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  ## json时间格式设置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    #模板引擎
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    #数据源
  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/rbac?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    #druid配置
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 1
        allow: 127.0.0.1
  #国际化配置
  messages:
    basename: i18n.login

  #redis配置
  redis:
    host: 127.0.0.1 # Redis服务器地址
    port: 6379   # Redis服务器连接端口
    password:   # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）
    database: 0 #Redis数据库索引（默认为0）


#mybatis-plus
mybatis-plus:
  global-config:
    banner: false
  #    别名
  type-aliases-package: cn.lhx.rbac.entity
  configuration:
    cache-enabled: true


